version: '3.8'

services:
  schelkovo-backend:
    container_name: schelkovo-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
    volumes:
      - schelkovo-data:/app
volumes:
  schelkovo-data: {}